# Generated by Django 3.2.6 on 2021-09-02 10:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت سفارش')),
                ('discount', models.IntegerField(blank=True, default=None, null=True, verbose_name='کد تخفیف')),
                ('status', models.CharField(choices=[('ordered', 'سفارش'), ('record', 'ثبت')], default='ordered', max_length=7, verbose_name='وضعیت سفارش')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('customer_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address', verbose_name='آدرس های مشتری')),
            ],
            options={
                'verbose_name_plural': 'سفارش ها',
                'ordering': ['order_date'],
            },
        ),
        migrations.CreateModel(
            name='PercentageOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نوع تخفیف')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='میزان تخفیف')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expired_time', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('active', models.BooleanField(default=False, verbose_name='وضعیت اعتبار')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name_plural': 'تخفیف های درصدی',
                'ordering': ['expired_time'],
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_price', models.IntegerField(verbose_name='قیمت کتاب')),
                ('book_quantity', models.PositiveSmallIntegerField(default=1, verbose_name='نعداد')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.book', verbose_name='کتاب')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='کد سفارش')),
            ],
            options={
                'verbose_name_plural': 'جزئیات سفارش',
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=6, unique=True, verbose_name='کد تخفیف')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='مقدار تخفیف')),
                ('valid_from', models.DateTimeField(verbose_name='تاریخ شروع تخفیف')),
                ('valid_to', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('active', models.BooleanField(default=False, verbose_name='وضعیت اعتبار')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name_plural': 'تخیف های امتیازی',
                'ordering': ['valid_to'],
            },
        ),
        migrations.CreateModel(
            name='CashOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نوع تخفیف')),
                ('value', models.IntegerField(verbose_name='مقدار تخیف')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expired_time', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('active', models.BooleanField(default=False, verbose_name='وضعیت اعتبار')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name_plural': 'تخفیف های نقدی',
                'ordering': ['expired_time'],
            },
        ),
    ]
