# Generated by Django 3.2.6 on 2021-08-11 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.BigIntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
            options={
                'verbose_name_plural': 'سبدهای خرید',
                'ordering': ['customer'],
            },
        ),
        migrations.CreateModel(
            name='PercentageOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=None)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('expired_time', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_percent_off', to='book.book')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_percent_off', to='book.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'تخفیف های درصدی',
                'ordering': ['expired_time'],
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('book_count', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ordered', 'سفارش'), ('record', 'ثبت')], default='ordered', max_length=7)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.book')),
                ('shop_basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_id', to='order.shoppingbasket')),
            ],
            options={
                'verbose_name_plural': 'جزئیات خرید',
            },
        ),
        migrations.CreateModel(
            name='CodeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=6)),
                ('value', models.IntegerField(default=None)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('expired_time', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'تخیف های امتیازی',
                'ordering': ['expired_time'],
            },
        ),
        migrations.CreateModel(
            name='CashOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=None)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('expired_time', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_cash_of', to='book.book')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_cash_off', to='book.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'تخفیف های نقدی',
                'ordering': ['expired_time'],
            },
        ),
    ]
