# Generated by Django 3.2.6 on 2021-08-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210811_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='book_price',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='cash_off',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='percent_off',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
